# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, Arun!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "HI This is my first sample Azure piepline"
    echo "This is the second Test i am doing" 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $root = 'https://api.p12.hmgroup.com:8201/api/payments/healthcheck'
      $user = "NnlCZThqSkxOcWhNVkFIKjRRbWtheWNzckhiUXFoTUxN"
      $pass= "Wng3VnVoVHMqNXlUNW1hbGxyaWdodFZCcm1NUEhyQndw"
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($Pair))
      $headers = @{ Authorization = "Basic $encodedCredentials" }
      $result = Invoke-WebRequest -Uri $url -Method Get -Headers $headers
      
    failOnStderr: true