# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, Arun!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "HI This is my first sample Azure piepline"
    echo "This is the second Test i am doing" 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $root = 'https://api.p12.hmgroup.com:8201/api/payments/healthcheck'
      $root1 = 'https://api.p12.hmgroup.com:8201/api/promotion/validatecoupon/'
      $user = "NnlCZThqSkxOcWhNVkFIKjRRbWtheWNzckhiUXFoTUxN"
      $pass= "Wng3VnVoVHMqNXlUNW1hbGxyaWdodFZCcm1NUEhyQndw"
      $Pair=  "$($user):$($pass)"
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($Pair))
      $headers = @{ Authorization = "Basic $encodedCredentials" }
      $resulthealth = Invoke-WebRequest -Uri $root -Method Get -Headers $headers

      $coupon = '{"CouponCode":"CouponTest1","UserEmail":"admin","CustomerExternalId":"277f7023881e4e4ead3865deb978bb0b","Market":"SWE"}'
      $json = ConvertFrom-Json –InputObject $coupon
      $resultjson = Invoke-WebRequest -Uri $root1 -Method POST -Headers $headers -Body $json -ContentType 'application/json'

    failOnStderr: true